---

- hosts: all
  become: yes
  gather_facts: false
  vars: 
   tomcat_port: 8086
  tasks:
   - name: updating rep
     yum:
      name: "*"
   - name: installing java
     yum:
      name: java-1.7.0-openjdk
   - name: setting default java
     alternatives:
      name: java
      link: /usr/bin/java
      path: /usr/lib/jvm/jre-1.7.0-openjdk/bin/java 
   - name: downloading tc
     get_url:
      url: https://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.61/bin/apache-tomcat-8.5.61.tar.gz
      dest: /usr/local
   - name: extracting tar file
     unarchive:
      src: /usr/local/apache-tomcat-8.5.61.tar.gz
      dest: /usr/local
      remote_src: yes
   - name: renaming tc home
     command: mv /usr/local/apache-tomcat-8.5.61 /usr/local/latest
     ignore_errors: yes
   - name: staring tc
     shell: nohup /usr/local/latest/bin/startup.sh
   - name: changing port dynamicaly
     template: 
      src: server.xml.j2
      dest: /usr/local/latest/conf/server.xml
      



