---
- hosts: all
  become: yes
  tasks:
  - name: install tc
    yum: 
     name: tomcat
  - name: copy jen war
    get_url:
     url: https://get.jenkins.io/war/2.272/jenkins.war
     dest: /usr/share/tomcat/webapps/jenkins.war
  - name: ser
    service: 
     name: tomcat
     state: started
     enabled: yes
